/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (2.4.8).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package au.org.consumerdatastandards.holder.api;

import au.org.consumerdatastandards.holder.model.CommonDiscoveryStatus;
import au.org.consumerdatastandards.holder.model.ResponseDiscoveryOutagesList;
import io.swagger.annotations.*;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RequestPart;
import org.springframework.web.multipart.MultipartFile;

import java.util.List;
import java.util.Map;
@Api(value = "CommonDiscovery", description = "the CommonDiscovery API")
public interface CommonDiscoveryApi {

    @ApiOperation(value = "Get Outages", nickname = "getOutages", notes = "Obtain a list of scheduled outages for the implementation", response = ResponseDiscoveryOutagesList.class, tags={  })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "Success", response = ResponseDiscoveryOutagesList.class) })
    @RequestMapping(value = "/discovery/outages",
        produces = {  }, 
        consumes = {  },
        method = RequestMethod.GET)
    ResponseEntity<ResponseDiscoveryOutagesList> getOutages(@ApiParam(value = "Minimum version of the API end point requested by the client. Must be set to a positive integer if provided. The data holder should respond with the highest supported version between [x-min-v](#request-headers) and [x-v](#request-headers). If all versions requested are not supported then the data holder should respond with a 406 Not Acceptable." ) @RequestHeader(value="x-min-v", required=false) String xMinV,@ApiParam(value = "Version of the API end point requested by the client. Must be set to a positive integer. The data holder should respond with the highest supported version between [x-min-v](#request-headers) and [x-v](#request-headers). If the value of [x-min-v](#request-headers) is equal to or higher than the value of [x-v](#request-headers) then the [x-min-v](#request-headers) header should be treated as absent. If all versions requested are not supported then the data holder should respond with a 406 Not Acceptable. See [HTTP Headers](#request-headers)" ) @RequestHeader(value="x-v", required=false) String xV);


    @ApiOperation(value = "Get Status", nickname = "getStatus", notes = "Obtain a health check status for the implementation", response = CommonDiscoveryStatus.class, tags={  })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "Success", response = CommonDiscoveryStatus.class) })
    @RequestMapping(value = "/discovery/status",
        produces = {  }, 
        consumes = {  },
        method = RequestMethod.GET)
    ResponseEntity<CommonDiscoveryStatus> getStatus(@ApiParam(value = "Minimum version of the API end point requested by the client. Must be set to a positive integer if provided. The data holder should respond with the highest supported version between [x-min-v](#request-headers) and [x-v](#request-headers). If all versions requested are not supported then the data holder should respond with a 406 Not Acceptable." ) @RequestHeader(value="x-min-v", required=false) String xMinV,@ApiParam(value = "Version of the API end point requested by the client. Must be set to a positive integer. The data holder should respond with the highest supported version between [x-min-v](#request-headers) and [x-v](#request-headers). If the value of [x-min-v](#request-headers) is equal to or higher than the value of [x-v](#request-headers) then the [x-min-v](#request-headers) header should be treated as absent. If all versions requested are not supported then the data holder should respond with a 406 Not Acceptable. See [HTTP Headers](#request-headers)" ) @RequestHeader(value="x-v", required=false) String xV);

}
