/*
 * Consumer Data Standards
 * Sample Data Holder to Demonstrate the Consumer Data Right APIs
 *
 * NOTE: This class is auto generated by the cds-codegen package
 * https://github.com/ConsumerDataStandardsAustralia/cds-codegen
 * Do not edit the class manually.
 */
package au.org.consumerdatastandards.holder.model;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonValue;

import javax.persistence.*;
import java.util.Objects;
import java.net.URI;
import java.lang.reflect.Field;

/**
 * BankingProductFeature
 * 
 * 
 */
@Entity
public class BankingProductFeature {
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    private Integer productFeatureId;

    // The type of feature described
    @JsonProperty("featureType")
    private FeatureType featureType;
    // Generic field containing additional information relevant to
    // the featureType specified. Whether mandatory or not is
    // dependent on the value of featureType
    @JsonProperty("additionalValue")
    @Column(length = 2048)
    private String additionalValue;
    // Display text providing more information on the feature.
    // Mandatory if the feature type is set to OTHER
    @JsonProperty("additionalInfo")
    @Column(length = 2048)
    private String additionalInfo;
    // Link to a web page with more information on this feature
    @JsonProperty("additionalInfoUri")
    private URI additionalInfoUri;

    public FeatureType getFeatureType() {
        return featureType;
    }

    public void setFeatureType(FeatureType featureType) {
        this.featureType = featureType;
    }

    public String getAdditionalValue() {
        return additionalValue;
    }

    public void setAdditionalValue(String additionalValue) {
        this.additionalValue = additionalValue;
    }

    public String getAdditionalInfo() {
        return additionalInfo;
    }

    public void setAdditionalInfo(String additionalInfo) {
        this.additionalInfo = additionalInfo;
    }

    public URI getAdditionalInfoUri() {
        return additionalInfoUri;
    }

    public void setAdditionalInfoUri(URI additionalInfoUri) {
        this.additionalInfoUri = additionalInfoUri;
    }

    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }

        BankingProductFeature inputModel = (BankingProductFeature) o;
        if (!(featureType.equals(inputModel.getFeatureType()))) {
            return false;
        }
        if (!(additionalValue.equals(inputModel.getAdditionalValue()))) {
            return false;
        }
        if (!(additionalInfo.equals(inputModel.getAdditionalInfo()))) {
            return false;
        }
        if (!(additionalInfoUri.equals(inputModel.getAdditionalInfoUri()))) {
            return false;
        }
        return true;
    }

    @Override
    public int hashCode() {
        return Objects.hash(additionalInfoUri, additionalInfoUri, additionalInfoUri, additionalInfoUri);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(String.format("class %s {\n", getClass()));

        for (Field oneField : getClass().getFields()) {
            oneField.setAccessible(true);
            try {
                sb.append(String.format("    %s: %s\n", oneField.getName(), (oneField.get(Object.class) == null ? "null"
                        : oneField.get(Object.class).toString().replace("\n", "\n    "))));
            } catch (IllegalArgumentException | IllegalAccessException e) {
                // I guess we won't print it
                sb.append(String.format("    %s, [unreadable]\n", oneField.getName()));
            }
        }
        sb.append("}");
        return sb.toString();
    }

    /**
     * FeatureType
     * 
     * 
     */
    public enum FeatureType {
        CARD_ACCESS("CARD_ACCESS"), ADDITIONAL_CARDS("ADDITIONAL_CARDS"), UNLIMITED_TXNS("UNLIMITED_TXNS"),
        FREE_TXNS("FREE_TXNS"), FREE_TXNS_ALLOWANCE("FREE_TXNS_ALLOWANCE"), LOYALTY_PROGRAM("LOYALTY_PROGRAM"),
        OFFSET("OFFSET"), OVERDRAFT("OVERDRAFT"), REDRAW("REDRAW"), INSURANCE("INSURANCE"),
        BALANCE_TRANSFERS("BALANCE_TRANSFERS"), INTEREST_FREE("INTEREST_FREE"),
        INTEREST_FREE_TRANSFERS("INTEREST_FREE_TRANSFERS"), DIGITAL_WALLET("DIGITAL_WALLET"),
        DIGITAL_BANKING("DIGITAL_BANKING"), NPP_PAYID("NPP_PAYID"), NPP_ENABLED("NPP_ENABLED"),
        DONATE_INTEREST("DONATE_INTEREST"), BILL_PAYMENT("BILL_PAYMENT"),
        COMPLEMENTARY_PRODUCT_DISCOUNTS("COMPLEMENTARY_PRODUCT_DISCOUNTS"), BONUS_REWARDS("BONUS_REWARDS"),
        NOTIFICATIONS("NOTIFICATIONS"), OTHER("OTHER");

        private String value;

        FeatureType(String value) {
            this.value = value;
        }

        @Override
        @JsonValue
        public String toString() {
            return String.valueOf(value);
        }

        @JsonCreator
        public static FeatureType fromValue(String value) {
            for (FeatureType b : FeatureType.values()) {
                if (b.value.equals(value)) {
                    return b;
                }
            }
            throw new IllegalArgumentException("Unexpected value '" + value + "'");
        }
    }

}
