/*
 * Consumer Data Standards
 * Sample Data Holder to Demonstrate the Consumer Data Right APIs
 *
 * NOTE: This class is auto generated by the codegen artefact
 * https://github.com/ConsumerDataStandardsAustralia/java-artefacts/codegen
 * Do not edit the class manually.
 */
package au.org.consumerdatastandards.holder.model;

/**
* The category to which a product or account belongs. See
* [here](#product-categories) for more details
*/
public enum BankingProductCategory {
    BUSINESS_LOANS,
    CRED_AND_CHRG_CARDS,
    LEASES,
    MARGIN_LOANS,
    OVERDRAFTS,
    PERS_LOANS,
    REGULATED_TRUST_ACCOUNTS,
    RESIDENTIAL_MORTGAGES,
    TERM_DEPOSITS,
    TRADE_FINANCE,
    TRAVEL_CARDS,
    TRANS_AND_SAVINGS_ACCOUNTS
}
