/*
 * Consumer Data Standards
 * Sample Data Holder to Demonstrate the Consumer Data Right APIs
 *
 * NOTE: This class is auto generated by the cds-codegen package
 * https://github.com/ConsumerDataStandardsAustralia/cds-codegen
 * Do not edit the class manually.
 */
package au.org.consumerdatastandards.holder.model;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonValue;

import javax.persistence.*;
import java.util.Objects;
import java.net.URI;
import java.lang.reflect.Field;

/**
 * BankingProductEligibility
 * 
 * 
 */
@Entity
public class BankingProductEligibility {

    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    private Integer productEligibilityId;
    // The type of eligibility criteria described. See the next
    // section for an overview of valid values and their meaning
    @JsonProperty("eligibilityType")
    private EligibilityType eligibilityType;
    // Generic field containing additional information relevant to
    // the eligibilityType specified. Whether mandatory or not is
    // dependent on the value of eligibilityType
    @JsonProperty("additionalValue")
    @Column(length = 2048)
    private String additionalValue;
    // Display text providing more information on the eligibility
    // criteria. Mandatory if the eligibilityType field is set to
    // OTHER
    @JsonProperty("additionalInfo")
    @Column(length = 2048)
    private String additionalInfo;
    // Link to a web page with more information on this eligibility
    // criteria
    @JsonProperty("additionalInfoUri")
    private URI additionalInfoUri;

    public EligibilityType getEligibilityType() {
        return eligibilityType;
    }

    public void setEligibilityType(EligibilityType eligibilityType) {
        this.eligibilityType = eligibilityType;
    }

    public String getAdditionalValue() {
        return additionalValue;
    }

    public void setAdditionalValue(String additionalValue) {
        this.additionalValue = additionalValue;
    }

    public String getAdditionalInfo() {
        return additionalInfo;
    }

    public void setAdditionalInfo(String additionalInfo) {
        this.additionalInfo = additionalInfo;
    }

    public URI getAdditionalInfoUri() {
        return additionalInfoUri;
    }

    public void setAdditionalInfoUri(URI additionalInfoUri) {
        this.additionalInfoUri = additionalInfoUri;
    }

    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }

        BankingProductEligibility inputModel = (BankingProductEligibility) o;
        if (!(eligibilityType.equals(inputModel.getEligibilityType()))) {
            return false;
        }
        if (!(additionalValue.equals(inputModel.getAdditionalValue()))) {
            return false;
        }
        if (!(additionalInfo.equals(inputModel.getAdditionalInfo()))) {
            return false;
        }
        if (!(additionalInfoUri.equals(inputModel.getAdditionalInfoUri()))) {
            return false;
        }
        return true;
    }

    @Override
    public int hashCode() {
        return Objects.hash(additionalInfoUri, additionalInfoUri, additionalInfoUri, additionalInfoUri);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(String.format("class %s {\n", getClass()));

        for (Field oneField : getClass().getFields()) {
            oneField.setAccessible(true);
            try {
                sb.append(String.format("    %s: %s\n", oneField.getName(), (oneField.get(Object.class) == null ? "null"
                        : oneField.get(Object.class).toString().replace("\n", "\n    "))));
            } catch (IllegalArgumentException | IllegalAccessException e) {
                // I guess we won't print it
                sb.append(String.format("    %s, [unreadable]\n", oneField.getName()));
            }
        }
        sb.append("}");
        return sb.toString();
    }

    /**
     * EligibilityType
     * 
     * 
     */
    public enum EligibilityType {
        BUSINESS("BUSINESS"), PENSION_RECIPIENT("PENSION_RECIPIENT"), MIN_AGE("MIN_AGE"), MAX_AGE("MAX_AGE"),
        MIN_INCOME("MIN_INCOME"), MIN_TURNOVER("MIN_TURNOVER"), STAFF("STAFF"), STUDENT("STUDENT"),
        EMPLOYMENT_STATUS("EMPLOYMENT_STATUS"), RESIDENCY_STATUS("RESIDENCY_STATUS"), NATURAL_PERSON("NATURAL_PERSON"),
        OTHER("OTHER");

        private String value;

        EligibilityType(String value) {
            this.value = value;
        }

        @Override
        @JsonValue
        public String toString() {
            return String.valueOf(value);
        }

        @JsonCreator
        public static EligibilityType fromValue(String value) {
            for (EligibilityType b : EligibilityType.values()) {
                if (b.value.equals(value)) {
                    return b;
                }
            }
            throw new IllegalArgumentException("Unexpected value '" + value + "'");
        }
    }

}
