FROM openjdk:8-jre
MAINTAINER Data61 <cdr-data61@csiro.au>

ENTRYPOINT ["/usr/bin/java", "-jar", "/opt/cds-client-java-cli/cli.jar"]

ARG JAR_FILE
ADD target/#[[$]]#{JAR_FILE} /opt/cds-client-java-cli/cli.jar
