/*
 * Consumer Data Standards
 * Sample Data Holder to Demonstrate the Consumer Data Right APIs
 *
 * NOTE: This class is auto generated by the cds-codegen package
 * https://github.com/ConsumerDataStandardsAustralia/cds-codegen
 * Do not edit the class manually.
 */
package au.org.consumerdatastandards.client.model;

/**
 * <p>The category to which a product or account belongs. See [here](#product-categories) for more
 * details
 */
public enum BankingEnumProductCategory {
  TRANS_AND_SAVINGS_ACCOUNTS,
  TERM_DEPOSITS,
  TRAVEL_CARDS,
  REGULATED_TRUST_ACCOUNTS,
  RESIDENTIAL_MORTGAGES,
  CRED_AND_CHRG_CARDS,
  PERS_LOANS,
  MARGIN_LOANS,
  LEASES,
  TRADE_FINANCE,
  OVERDRAFTS,
  BUSINESS_LOANS
}
