/*
 * Consumer Data Standards
 * Sample client library to Demonstrate the Consumer Data Right APIs
 *
 * NOTE: This class is auto generated by the codegen artefact
 * https://github.com/ConsumerDataStandardsAustralia/java-artefacts/codegen
 */
package au.org.consumerdatastandards.client.model;

import java.util.Objects;

public class RequestAccountIds {

    private RequestAccountIdsData data;

    private Object meta;

    /**
     * Get data
     * @return data
     */
    public RequestAccountIdsData getData() {
        return data;
    }

    public void setData(RequestAccountIdsData data) {
        this.data = data;
    }

    /**
     * Get meta
     * @return meta
     */
    public Object getMeta() {
        return meta;
    }

    public void setMeta(Object meta) {
        this.meta = meta;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        RequestAccountIds requestAccountIds = (RequestAccountIds) o;
        return Objects.equals(this.data, requestAccountIds.data) &&
            Objects.equals(this.meta, requestAccountIds.meta);
    }

    @Override
    public int hashCode() {
        return Objects.hash(
            data,
            meta);
    }

    @Override
    public String toString() {
        return "class RequestAccountIds {\n" +
            "   data: " + toIndentedString(data) + "\n" + 
            "   meta: " + toIndentedString(meta) + "\n" + 
            "}";
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }
}
