/*
 * Consumer Data Standards
 * Sample client library to Demonstrate the Consumer Data Right APIs
 *
 * NOTE: This class is auto generated by the codegen artefact
 * https://github.com/ConsumerDataStandardsAustralia/java-artefacts/codegen
 */
package au.org.consumerdatastandards.client.model;

import java.util.Objects;

public class RequestAccountIds {

    private RequestAccountIdsData data;

    private Object Object;

    /**
     * Get data
     * @return data
     */
    public RequestAccountIdsData getData() {
        return data;
    }

    public void setData(RequestAccountIdsData data) {
        this.data = data;
    }

    /**
     * Get Object
     * @return Object
     */
    public Object getObject() {
        return Object;
    }

    public void setObject(Object Object) {
        this.Object = Object;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        RequestAccountIds requestAccountIds = (RequestAccountIds) o;
        return Objects.equals(this.data, requestAccountIds.data) &&
            Objects.equals(this.Object, requestAccountIds.Object);
    }

    @Override
    public int hashCode() {
        return Objects.hash(
            data,
            Object);
    }

    @Override
    public String toString() {
        return "class RequestAccountIds {\n" +
            "   data: " + toIndentedString(data) + "\n" + 
            "   Object: " + toIndentedString(Object) + "\n" + 
            "}";
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }
}
